### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by mashuDuek** [omarluq/stimulus-store#23]
There is a typo in [this line](https://github.com/omarluq/stimulus-store/blob/9e524f76c3874b031814a4598f0113df12849492/README.md?plain=1#L172C92-L172C92) in the README. 

Instead of:
>When you call `useStore(this)` in the connect method, the `useStore` hook will subscriber the controller to all the stores specified in the static stores array.

Should be:
>When you call `useStore(this)` in the connect method, the `useStore` hook will subscribe the controller to all the stores specified in the static stores array.

**Comment by omarluq** [comment]
Ty!
