### ISSUE TITLE
Reevaluating the use of Yarn and Rollup

### ISSUE THREAD

**Issue by omarluq** [omarluq/stimulus-store#35]
**Is your feature request related to a problem? Please describe.**
Reevaluating the use of Yarn and Rollup. While they are effective, I believe there might benefit from exploring newer tools like pnpm or Bun, particularly in terms of package management and the build process. My goal is to identify if there are more efficient ways to manage dependencies and build the library.

**Describe the solution you'd like**
I am considering a switch from Yarn to either pnpm or Bun for package management. pnpm is appealing for its efficient node_modules handling, and Bun has been noted for its impressive performance. Furthermore, Bun's integrated bundling capabilities present an intriguing possibility for simplifying the build process, potentially taking over the role currently filled by Rollup. The goal is to streamline workflow and possibly improve build times.

**Comment by tcarac** [comment]
I think pnpm makes sense, given bun is still a bit early for some of the features we want to support like cjs.

**Comment by omarluq** [comment]
@tcarac that make sense! do you wanna take on moving from yarn to slim?
