### ISSUE TITLE
Add contributor

### ISSUE THREAD

**Issue by omarluq** [omarluq/stimulus-store#41]

**Comment by omarluq** [comment]
@all-contributors please add @tcarac for code, bug, doc, ideas, infra, maintenance, review, question, platform

**Comment by omarluq** [comment]
@all-contributors please add @tcarac for code, bug, doc, ideas, infra, maintenance, review, question, platform

**Comment by omarluq** [comment]
@all-contributors please add @omarluq for code

**Comment by omarluq** [comment]
@all-contributors please add @tcarac for code

**Comment by tcarac** [comment]
@omarluq can we close this ?
