### ISSUE TITLE
Link to docs in README is broken (404).

### ISSUE THREAD

**Issue by edk** [omarluq/stimulus-store#69]
**Describe the bug**
Link in readme to docs is broken (404)

**To Reproduce**
[Steps to reproduce the behavior:]
In the readme it says to go to: (https://github.com/omarluq/stimulus-store/blob/main/docs/www.stimulus-store.com)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

Just trying to get a feel for the project, and see how it could be used.

**Comment by omarluq** [comment]
Thank you for reporting!
